apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-cluster
  namespace: my-elastic-project
spec:
  version: 8.5.3
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false


# spec:
#   http:
#     service:
#       metadata:
#         name: elasticsearch-cluster-es-http
#         namespace: my-elastic-project
#       spec:
#         type: NodePort
#         ports:
#         - name: elasticsearch-cluster-es-http-np
#           port: 9200
#           targetPort: 9200
#           nodePort: 30040
#           protocol: TCP
#     tls:
#       selfSignedCertificate:
#         disabled: true


# spec:
#   nodeSets:
#   - name: masters
#     count: 3
#     config:
#       # On Elasticsearch versions before 7.9.0, replace the node.roles configuration with the following:
#       # node.master: true
#       node.roles: ["master"]
#       xpack.ml.enabled: true
#       node.remote_cluster_client: false
#   - name: data
#     count: 10
#     config:
#       # On Elasticsearch versions before 7.9.0, replace the node.roles configuration with the following:
#       # node.master: false
#       # node.data: true
#       # node.ingest: true
#       # node.ml: true
#       # node.transform: true
#       node.roles: ["data", "ingest", "ml", "transform"]
#       node.remote_cluster_client: false