apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: elasticsearch-kibana
  namespace: my-elastic-project
spec:
  version: 8.5.3
  count: 1
  elasticsearchRef:
    name: elasticsearch-cluster
    namespace: my-elastic-project